
.macro output_buffer_data
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
        inc isrtmp2                     ; (1)
        out PORTC, isrtmp2              ; (1)
.endmacro
